targets:
  $default:
    builders:
      auto_route_generator:auto_router_generator:
        generate_for:
          - lib/src/common/config/router/app_router.dart
      auto_route_generator:auto_route_generator:
        generate_for:
          - lib/src/presentation/**.dart
      source_gen|combining_builder:
        options:
          build_extensions:
            '^lib/{{}}.dart': 'lib/generated/{{}}.g.dart'
