name: personal_expenses_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  
  
  # Localization
  intl: ^0.19.0
  flutter_localizations:
    sdk: flutter

  # State management
  mobx: ^2.3.3+2
  provider: ^6.1.2
  flutter_mobx: ^2.2.1+1

  # Data
  drift: ^2.20.2
  drift_flutter: ^0.1.0
  equatable: ^2.0.5
  shared_preferences: ^2.3.2
  cached_network_image: ^3.4.1

  # Navigation
  auto_route: ^9.2.2

  # Utility
  get_it: ^8.0.0
  talker_flutter: ^4.4.1

  # UI
  cupertino_icons: ^1.0.8
  shimmer: ^3.0.0
  lottie: ^3.1.2
  flutter_svg: ^2.0.10+1
  transparent_image: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

  # Code generation
  build_runner: ^2.4.12
  flutter_gen_runner: ^5.7.0
  auto_route_generator: ^9.0.0

  # State management
  mobx_codegen: ^2.6.1

  # Data
  drift_dev: ^2.20.3

flutter:
  uses-material-design: true
  assets:
    - assets/color/
    - assets/images/
    - assets/icons/

  fonts:
    - family: Comfortaa
      fonts:
        - asset: assets/fonts/Comfortaa-Regular.ttf
        - asset: assets/fonts/Comfortaa-Medium.ttf
        - asset: assets/fonts/Comfortaa-Bold.ttf

flutter_gen:
  output: lib/generated/
  line_length: 120

  # Optional
  integrations:
    flutter_svg: true
    lottie: true

  colors:
    inputs:
      - assets/color/colors.xml
